### PR TITLE
Implementation of harp-dataset

### PR DESCRIPTION
**Pull request by ElessarWebb**
- [x] Refactor global_attributes into harp_product_metadata
- [x] Add harp_dataset_add_file
- [x] Add harp_dataset_add_directory
- [x] Refactor harp_collocation_result to use harp_dataset and harp_product_metadata properly.
- [x] Test that things still work

The last task is not as trivial as it sounds, mostly because we want to build harp_collocation_result instances without requiring the reading of a whole directory of products.
We therefor split the task in two:

- [x] Refactor harp_collocation_result to a less string-centered, more efficient representation
- [ ] ~~Add a function fx that takes a harp_collocation_result and a directory and builds a dataset that stores the metadata for all the files associated with products that appear in the result set.~~ (next PR)

Important operations  on datasets and collocation results to optimize for are:

- `harp_dataset_add_file` (for incremental builds of datasets using e.g. `harp_dataset_add_directory`),
- `harp_collocation_result_read`: Read a result csv file¸
- `harp_collocation_result_read_metadata`: Building a dataset from a directory associated with a harp_collocation result
- finding the product metadata associated with an entry in a collocation_result, assuming that we have the associated dataset.

Therefor we propose the following representations:

### Harp product metadata

```
struct harp_product_metadata_struct {
    char *filename; /* can be NULL if no file is associated with the product */
    double datetime_start;
    double datetime_stop;
    long dimension[HARP_NUM_DIM_TYPES];
    char *source_product;
};
```

A downside of this representation is that for the following sequence of operations, we end up with a metadata instance `m` without a filename, even though it exists:

`harp_import_product(.., p) -> harp_product_get_metadata(p, m)`

### Harp dataset

```
/** HARP Dataset struct */
struct harp_dataset_struct {
    hashtable_struct *source_to_index; /* maps product_source names to indices */
    char **product_source; /* set of product sources - every source appears only once */
    int num_metadata;
    harp_product_metadata **metadata; /* stores metadata for source in product_source */
};

/** HARP Dataset typedef */
typedef struct harp_dataset_struct harp_dataset;
```

### Harp collocation results

```
struct harp_collocation_pair_struct
{
    long collocation_index;
    int product_index_a;  /* index into dataset_a of associated collocation result */
    long sample_index_a;
    int product_index_b;  /* index into dataset_b of associated collocation result */
    long sample_index_b;
    double difference[HARP_COLLOCATION_RESULT_MAX_NUM_DIFFERENCES];
};

/** HARP Collocation result */
struct harp_collocation_result {
    harp_dataset dataset_a;
    harp_dataset dataset_b;
    int difference_available[HARP_COLLOCATION_RESULT_MAX_NUM_DIFFERENCES];
    char *difference_unit[HARP_COLLOCATION_RESULT_MAX_NUM_DIFFERENCES];
    int num_pairs;
    harp_collocation_pair **pair;
};
```

harp_dataset can have it's attribute `metadata == NULL` to indicate that no metadata is known for it's product's sources.

`harp_collocation_result->pair` can be sorted as before.

### CODE REVIEW

**Comment by svniemeijer** [comment]
How about harp_dataset_add_file() and harp_dataset_add_directory() to append items to a dataset (instead of harp_dataset_import())?
harp_dataset_add_directory() would then internally call harp_dataset_add_file() again.

**Comment by ElessarWebb** [comment]
SGTM

**Comment by ElessarWebb** [comment]
Edit: updated the proposed representation of harp_dataset and harp_collocation_result;

**Comment by ElessarWebb** [comment]
Edit: Added last task before PR completion: testing if the refactored version of harp_collocate has the same output as the version in master.

**Comment by ElessarWebb** [comment]
Tested result of harpcollocate matchup and up-to-date with master. Ready to merge.

**Comment by svniemeijer** [comment]
Still an additional issue needs to be resolved. A ``harpfilter -a 'collocate-left("collocations.csv")'`` does not produce the same results as for master. This branch gives an error about a source product not existing.

**Comment by ElessarWebb** [comment]
With these commits this branch outputs the same results as master on the test datasets.

**Pull request merged**
